export const MARKET_CONFIGS = {
  US: {
    id: 'US',
    label: 'United States',
    shortLabel: 'US staffing',
    currency: 'USD',
    dateFormat: 'MM/DD/YYYY',
    defaultTimezone: 'America/New_York',
    timezoneOptions: ['America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles'],
    businessHours: { start: '09:00', end: '18:00' },
    phonePlaceholder: '+1 555 000 0000',
    locationPlaceholder: 'New York, NY / Remote',
    candidateLocationPlaceholder: 'City, State',
    workAuthLabel: 'Work Auth',
    defaultWorkAuth: 'US Citizen',
    workAuthOptions: ['US Citizen', 'Green Card', 'H1B', 'OPT/CPT', 'TN Visa', 'Other'],
    rateLabel: 'Bill Rate',
    candidateRateLabel: 'Bill Rate',
    ratePlaceholder: '$80-100/hr',
    candidateRatePlaceholder: '$85/hr',
    billRatePlaceholder: '$95/hr',
    payRatePlaceholder: '$70/hr',
    employmentTypes: ['Contract', 'Full-time', 'Contract-to-Hire', 'Part-time'],
    ownershipTitle: 'Front End / Ownership',
    ownerLabel: 'FE Name',
    ownerPlaceholder: 'Sarah K.',
    ownerExtensionLabel: 'Extension',
    ownerExtensionPlaceholder: 'x204',
    accountManagerPlaceholder: 'Mike R.',
    notesPlaceholder: 'Internal notes, visa constraints, rate flexibility...',
    descriptionHint: 'Use US staffing defaults for authorization, W2/C2C-style rates, and client submittals.',
    highlights: ['USD rates', 'US visa statuses', 'W2/C2C-ready workflow'],
  },
  IN: {
    id: 'IN',
    label: 'India',
    shortLabel: 'India staffing',
    currency: 'INR',
    dateFormat: 'DD/MM/YYYY',
    defaultTimezone: 'Asia/Kolkata',
    timezoneOptions: ['Asia/Kolkata'],
    businessHours: { start: '09:30', end: '18:30' },
    phonePlaceholder: '+91 98765 43210',
    locationPlaceholder: 'Bengaluru, KA / Remote',
    candidateLocationPlaceholder: 'City, State / Remote',
    workAuthLabel: 'Eligibility',
    defaultWorkAuth: 'Indian Citizen',
    workAuthOptions: ['Indian Citizen', 'OCI', 'Work Permit', 'Dependent Visa', 'Other'],
    rateLabel: 'Budget / CTC',
    candidateRateLabel: 'Expected CTC / Rate',
    ratePlaceholder: '₹18-24 LPA',
    candidateRatePlaceholder: '₹22 LPA or ₹1,800/hr',
    billRatePlaceholder: '₹2,500/hr or ₹30 LPA',
    payRatePlaceholder: '₹1,800/hr or ₹22 LPA',
    employmentTypes: ['Full-time', 'Contract', 'Contract-to-Hire', 'Third-party Payroll', 'Consulting'],
    ownershipTitle: 'Delivery / Ownership',
    ownerLabel: 'Delivery Owner',
    ownerPlaceholder: 'Priya S.',
    ownerExtensionLabel: 'Desk / Ext',
    ownerExtensionPlaceholder: 'BLR-204',
    accountManagerPlaceholder: 'Amit R.',
    notesPlaceholder: 'Notice period, current CTC, expected CTC, preferred location...',
    descriptionHint: 'Use India staffing defaults for INR compensation, CTC, notice period, and local eligibility.',
    highlights: ['INR compensation', 'CTC and notice period notes', 'India eligibility options'],
  },
}

export const MARKET_OPTIONS = Object.values(MARKET_CONFIGS).map(market => ({
  value: market.id,
  label: market.label,
  desc: market.descriptionHint,
}))

export function getMarketConfig(marketId) {
  return MARKET_CONFIGS[marketId] || MARKET_CONFIGS.US
}
